// This file was auto-generated by Flurl.Http.CodeGen. Do not edit directly.

using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Flurl.Http.Content;

namespace Flurl.Http
{
	public static class HttpExtensions
	{
		/// <summary>
		/// Sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> GetAsync(this FlurlClient client, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Get, cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> GetAsync(this FlurlClient client) {
			return client.SendAsync(HttpMethod.Get);
		}

		/// <summary>
		/// Sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the JSON response body deserialized to an object of type T.</returns>
		public static Task<T> GetJsonAsync<T>(this FlurlClient client, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveJson<T>();
		}

		/// <summary>
		/// Sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the JSON response body deserialized to an object of type T.</returns>
		public static Task<T> GetJsonAsync<T>(this FlurlClient client) {
			return client.SendAsync(HttpMethod.Get).ReceiveJson<T>();
		}

		/// <summary>
		/// Sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the JSON response body deserialized to a dynamic.</returns>
		public static Task<dynamic> GetJsonAsync(this FlurlClient client, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveJson();
		}

		/// <summary>
		/// Sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the JSON response body deserialized to a dynamic.</returns>
		public static Task<dynamic> GetJsonAsync(this FlurlClient client) {
			return client.SendAsync(HttpMethod.Get).ReceiveJson();
		}

		/// <summary>
		/// Sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the JSON response body deserialized to a list of dynamics.</returns>
		public static Task<IList<dynamic>> GetJsonListAsync(this FlurlClient client, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveJsonList();
		}

		/// <summary>
		/// Sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the JSON response body deserialized to a list of dynamics.</returns>
		public static Task<IList<dynamic>> GetJsonListAsync(this FlurlClient client) {
			return client.SendAsync(HttpMethod.Get).ReceiveJsonList();
		}

		/// <summary>
		/// Sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the response body as a string.</returns>
		public static Task<string> GetStringAsync(this FlurlClient client, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveString();
		}

		/// <summary>
		/// Sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the response body as a string.</returns>
		public static Task<string> GetStringAsync(this FlurlClient client) {
			return client.SendAsync(HttpMethod.Get).ReceiveString();
		}

		/// <summary>
		/// Sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the response body as a Stream.</returns>
		public static Task<Stream> GetStreamAsync(this FlurlClient client, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveStream();
		}

		/// <summary>
		/// Sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the response body as a Stream.</returns>
		public static Task<Stream> GetStreamAsync(this FlurlClient client) {
			return client.SendAsync(HttpMethod.Get).ReceiveStream();
		}

		/// <summary>
		/// Sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the response body as a byte array.</returns>
		public static Task<byte[]> GetBytesAsync(this FlurlClient client, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveBytes();
		}

		/// <summary>
		/// Sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the response body as a byte array.</returns>
		public static Task<byte[]> GetBytesAsync(this FlurlClient client) {
			return client.SendAsync(HttpMethod.Get).ReceiveBytes();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> GetAsync(this Url url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get, cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> GetAsync(this Url url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the JSON response body deserialized to an object of type T.</returns>
		public static Task<T> GetJsonAsync<T>(this Url url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveJson<T>();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the JSON response body deserialized to an object of type T.</returns>
		public static Task<T> GetJsonAsync<T>(this Url url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get).ReceiveJson<T>();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the JSON response body deserialized to a dynamic.</returns>
		public static Task<dynamic> GetJsonAsync(this Url url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveJson();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the JSON response body deserialized to a dynamic.</returns>
		public static Task<dynamic> GetJsonAsync(this Url url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get).ReceiveJson();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the JSON response body deserialized to a list of dynamics.</returns>
		public static Task<IList<dynamic>> GetJsonListAsync(this Url url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveJsonList();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the JSON response body deserialized to a list of dynamics.</returns>
		public static Task<IList<dynamic>> GetJsonListAsync(this Url url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get).ReceiveJsonList();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the response body as a string.</returns>
		public static Task<string> GetStringAsync(this Url url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveString();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the response body as a string.</returns>
		public static Task<string> GetStringAsync(this Url url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get).ReceiveString();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the response body as a Stream.</returns>
		public static Task<Stream> GetStreamAsync(this Url url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveStream();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the response body as a Stream.</returns>
		public static Task<Stream> GetStreamAsync(this Url url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get).ReceiveStream();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the response body as a byte array.</returns>
		public static Task<byte[]> GetBytesAsync(this Url url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveBytes();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the response body as a byte array.</returns>
		public static Task<byte[]> GetBytesAsync(this Url url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get).ReceiveBytes();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> GetAsync(this string url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get, cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> GetAsync(this string url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the JSON response body deserialized to an object of type T.</returns>
		public static Task<T> GetJsonAsync<T>(this string url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveJson<T>();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the JSON response body deserialized to an object of type T.</returns>
		public static Task<T> GetJsonAsync<T>(this string url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get).ReceiveJson<T>();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the JSON response body deserialized to a dynamic.</returns>
		public static Task<dynamic> GetJsonAsync(this string url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveJson();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the JSON response body deserialized to a dynamic.</returns>
		public static Task<dynamic> GetJsonAsync(this string url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get).ReceiveJson();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the JSON response body deserialized to a list of dynamics.</returns>
		public static Task<IList<dynamic>> GetJsonListAsync(this string url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveJsonList();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the JSON response body deserialized to a list of dynamics.</returns>
		public static Task<IList<dynamic>> GetJsonListAsync(this string url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get).ReceiveJsonList();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the response body as a string.</returns>
		public static Task<string> GetStringAsync(this string url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveString();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the response body as a string.</returns>
		public static Task<string> GetStringAsync(this string url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get).ReceiveString();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the response body as a Stream.</returns>
		public static Task<Stream> GetStreamAsync(this string url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveStream();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the response body as a Stream.</returns>
		public static Task<Stream> GetStreamAsync(this string url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get).ReceiveStream();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the response body as a byte array.</returns>
		public static Task<byte[]> GetBytesAsync(this string url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get, cancellationToken: cancellationToken).ReceiveBytes();
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous GET request.
		/// </summary>
		/// <returns>A Task whose result is the response body as a byte array.</returns>
		public static Task<byte[]> GetBytesAsync(this string url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Get).ReceiveBytes();
		}

		/// <summary>
		/// Sends an asynchronous POST request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostAsync(this FlurlClient client, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Post, cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Sends an asynchronous POST request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostAsync(this FlurlClient client) {
			return client.SendAsync(HttpMethod.Post);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous POST request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostAsync(this Url url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Post, cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous POST request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostAsync(this Url url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Post);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous POST request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostAsync(this string url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Post, cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous POST request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostAsync(this string url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Post);
		}

		/// <summary>
		/// Sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostJsonAsync(this FlurlClient client, object data, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Post, content: new CapturedJsonContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostJsonAsync(this FlurlClient client, object data) {
			return client.SendAsync(HttpMethod.Post, content: new CapturedJsonContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostJsonAsync(this Url url, object data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Post, content: new CapturedJsonContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostJsonAsync(this Url url, object data) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Post, content: new CapturedJsonContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostJsonAsync(this string url, object data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Post, content: new CapturedJsonContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostJsonAsync(this string url, object data) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Post, content: new CapturedJsonContent(data));
		}

		/// <summary>
		/// Sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostStringAsync(this FlurlClient client, string data, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Post, content: new CapturedStringContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostStringAsync(this FlurlClient client, string data) {
			return client.SendAsync(HttpMethod.Post, content: new CapturedStringContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostStringAsync(this Url url, string data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Post, content: new CapturedStringContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostStringAsync(this Url url, string data) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Post, content: new CapturedStringContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostStringAsync(this string url, string data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Post, content: new CapturedStringContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostStringAsync(this string url, string data) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Post, content: new CapturedStringContent(data));
		}

		/// <summary>
		/// Sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostUrlEncodedAsync(this FlurlClient client, object data, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Post, content: new CapturedUrlEncodedContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostUrlEncodedAsync(this FlurlClient client, object data) {
			return client.SendAsync(HttpMethod.Post, content: new CapturedUrlEncodedContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostUrlEncodedAsync(this Url url, object data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Post, content: new CapturedUrlEncodedContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostUrlEncodedAsync(this Url url, object data) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Post, content: new CapturedUrlEncodedContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostUrlEncodedAsync(this string url, object data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Post, content: new CapturedUrlEncodedContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous POST request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PostUrlEncodedAsync(this string url, object data) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Post, content: new CapturedUrlEncodedContent(data));
		}

		/// <summary>
		/// Sends an asynchronous HEAD request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> HeadAsync(this FlurlClient client, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Head, cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Sends an asynchronous HEAD request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> HeadAsync(this FlurlClient client) {
			return client.SendAsync(HttpMethod.Head);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous HEAD request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> HeadAsync(this Url url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Head, cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous HEAD request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> HeadAsync(this Url url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Head);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous HEAD request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> HeadAsync(this string url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Head, cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous HEAD request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> HeadAsync(this string url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Head);
		}

		/// <summary>
		/// Sends an asynchronous PUT request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutAsync(this FlurlClient client, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Put, cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Sends an asynchronous PUT request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutAsync(this FlurlClient client) {
			return client.SendAsync(HttpMethod.Put);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PUT request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutAsync(this Url url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Put, cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PUT request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutAsync(this Url url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Put);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PUT request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutAsync(this string url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Put, cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PUT request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutAsync(this string url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Put);
		}

		/// <summary>
		/// Sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutJsonAsync(this FlurlClient client, object data, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Put, content: new CapturedJsonContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutJsonAsync(this FlurlClient client, object data) {
			return client.SendAsync(HttpMethod.Put, content: new CapturedJsonContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutJsonAsync(this Url url, object data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Put, content: new CapturedJsonContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutJsonAsync(this Url url, object data) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Put, content: new CapturedJsonContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutJsonAsync(this string url, object data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Put, content: new CapturedJsonContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutJsonAsync(this string url, object data) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Put, content: new CapturedJsonContent(data));
		}

		/// <summary>
		/// Sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutStringAsync(this FlurlClient client, string data, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Put, content: new CapturedStringContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutStringAsync(this FlurlClient client, string data) {
			return client.SendAsync(HttpMethod.Put, content: new CapturedStringContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutStringAsync(this Url url, string data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Put, content: new CapturedStringContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutStringAsync(this Url url, string data) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Put, content: new CapturedStringContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutStringAsync(this string url, string data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Put, content: new CapturedStringContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutStringAsync(this string url, string data) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Put, content: new CapturedStringContent(data));
		}

		/// <summary>
		/// Sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutUrlEncodedAsync(this FlurlClient client, object data, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Put, content: new CapturedUrlEncodedContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutUrlEncodedAsync(this FlurlClient client, object data) {
			return client.SendAsync(HttpMethod.Put, content: new CapturedUrlEncodedContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutUrlEncodedAsync(this Url url, object data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Put, content: new CapturedUrlEncodedContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutUrlEncodedAsync(this Url url, object data) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Put, content: new CapturedUrlEncodedContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutUrlEncodedAsync(this string url, object data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Put, content: new CapturedUrlEncodedContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PUT request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PutUrlEncodedAsync(this string url, object data) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Put, content: new CapturedUrlEncodedContent(data));
		}

		/// <summary>
		/// Sends an asynchronous DELETE request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> DeleteAsync(this FlurlClient client, CancellationToken cancellationToken) {
			return client.SendAsync(HttpMethod.Delete, cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Sends an asynchronous DELETE request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> DeleteAsync(this FlurlClient client) {
			return client.SendAsync(HttpMethod.Delete);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous DELETE request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> DeleteAsync(this Url url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Delete, cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous DELETE request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> DeleteAsync(this Url url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Delete);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous DELETE request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> DeleteAsync(this string url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Delete, cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous DELETE request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> DeleteAsync(this string url) {
			return new FlurlClient(url, false).SendAsync(HttpMethod.Delete);
		}

		/// <summary>
		/// Sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchAsync(this FlurlClient client, CancellationToken cancellationToken) {
			return client.SendAsync(new HttpMethod("PATCH"), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Sends an asynchronous PATCH request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchAsync(this FlurlClient client) {
			return client.SendAsync(new HttpMethod("PATCH"));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchAsync(this Url url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(new HttpMethod("PATCH"), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PATCH request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchAsync(this Url url) {
			return new FlurlClient(url, false).SendAsync(new HttpMethod("PATCH"));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchAsync(this string url, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(new HttpMethod("PATCH"), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PATCH request.
		/// </summary>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchAsync(this string url) {
			return new FlurlClient(url, false).SendAsync(new HttpMethod("PATCH"));
		}

		/// <summary>
		/// Sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchJsonAsync(this FlurlClient client, object data, CancellationToken cancellationToken) {
			return client.SendAsync(new HttpMethod("PATCH"), content: new CapturedJsonContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchJsonAsync(this FlurlClient client, object data) {
			return client.SendAsync(new HttpMethod("PATCH"), content: new CapturedJsonContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchJsonAsync(this Url url, object data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(new HttpMethod("PATCH"), content: new CapturedJsonContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchJsonAsync(this Url url, object data) {
			return new FlurlClient(url, false).SendAsync(new HttpMethod("PATCH"), content: new CapturedJsonContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchJsonAsync(this string url, object data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(new HttpMethod("PATCH"), content: new CapturedJsonContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchJsonAsync(this string url, object data) {
			return new FlurlClient(url, false).SendAsync(new HttpMethod("PATCH"), content: new CapturedJsonContent(data));
		}

		/// <summary>
		/// Sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchStringAsync(this FlurlClient client, string data, CancellationToken cancellationToken) {
			return client.SendAsync(new HttpMethod("PATCH"), content: new CapturedStringContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchStringAsync(this FlurlClient client, string data) {
			return client.SendAsync(new HttpMethod("PATCH"), content: new CapturedStringContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchStringAsync(this Url url, string data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(new HttpMethod("PATCH"), content: new CapturedStringContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchStringAsync(this Url url, string data) {
			return new FlurlClient(url, false).SendAsync(new HttpMethod("PATCH"), content: new CapturedStringContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchStringAsync(this string url, string data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(new HttpMethod("PATCH"), content: new CapturedStringContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchStringAsync(this string url, string data) {
			return new FlurlClient(url, false).SendAsync(new HttpMethod("PATCH"), content: new CapturedStringContent(data));
		}

		/// <summary>
		/// Sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchUrlEncodedAsync(this FlurlClient client, object data, CancellationToken cancellationToken) {
			return client.SendAsync(new HttpMethod("PATCH"), content: new CapturedUrlEncodedContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchUrlEncodedAsync(this FlurlClient client, object data) {
			return client.SendAsync(new HttpMethod("PATCH"), content: new CapturedUrlEncodedContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchUrlEncodedAsync(this Url url, object data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(new HttpMethod("PATCH"), content: new CapturedUrlEncodedContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchUrlEncodedAsync(this Url url, object data) {
			return new FlurlClient(url, false).SendAsync(new HttpMethod("PATCH"), content: new CapturedUrlEncodedContent(data));
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchUrlEncodedAsync(this string url, object data, CancellationToken cancellationToken) {
			return new FlurlClient(url, false).SendAsync(new HttpMethod("PATCH"), content: new CapturedUrlEncodedContent(data), cancellationToken: cancellationToken);
		}

		/// <summary>
		/// Creates a FlurlClient from the URL and sends an asynchronous PATCH request.
		/// </summary>
		/// <param name="data">Contents of the request body.</param>
		/// <returns>A Task whose result is the received HttpResponseMessage.</returns>
		public static Task<HttpResponseMessage> PatchUrlEncodedAsync(this string url, object data) {
			return new FlurlClient(url, false).SendAsync(new HttpMethod("PATCH"), content: new CapturedUrlEncodedContent(data));
		}

	}
}
